DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
`order_id` INTEGER PRIMARY KEY AUTOINCREMENT,
`invoice_no` INT  NOT NULL DEFAULT '0',
`invoice_prefix` TEXT NOT NULL DEFAULT 'INV-',
`site_id` tinyINTEGER NOT NULL DEFAULT '0',
`store_name` TEXT NOT NULL,
`store_url` TEXT NOT NULL,
`user_id` INT  NOT NULL DEFAULT '0',
`user_group_id` INT  NOT NULL DEFAULT '0',
`first_name` TEXT NOT NULL,
`last_name` TEXT NOT NULL,
`email` TEXT NOT NULL,
`phone_number` TEXT NOT NULL DEFAULT '',
`fax` TEXT NOT NULL,
`custom_field` text NOT NULL,
`billing_first_name` TEXT NOT NULL,
`billing_last_name` TEXT NOT NULL,
`billing_company` TEXT NOT NULL,
`billing_address_1` TEXT NOT NULL,
`billing_address_2` TEXT NOT NULL,
`billing_city` TEXT NOT NULL,
`billing_postcode` TEXT NOT NULL,
`billing_country` TEXT NOT NULL,
`billing_country_id` INT  NOT NULL,
`billing_zone` TEXT NOT NULL,
`billing_zone_id` INT  NOT NULL,
`billing_address_format` text NOT NULL,
`billing_custom_field` text NOT NULL,
`billing_method` TEXT NOT NULL,
`billing_code` TEXT NOT NULL,
`shipping_first_name` TEXT NOT NULL DEFAULT '',
`shipping_last_name` TEXT NOT NULL DEFAULT '',
`shipping_company` TEXT NOT NULL DEFAULT '',
`shipping_address_1` TEXT NOT NULL DEFAULT '',
`shipping_address_2` TEXT NOT NULL DEFAULT '',
`shipping_city` TEXT NOT NULL DEFAULT '',
`shipping_postcode` TEXT NOT NULL DEFAULT '',
`shipping_country` TEXT NOT NULL,
`shipping_country_id` INT  NOT NULL DEFAULT 0,
`shipping_zone` TEXT NOT NULL,
`shipping_zone_id` INT  NOT NULL DEFAULT 0,
`shipping_address_format` text NOT NULL,
`shipping_custom_field` text NOT NULL,
`shipping_method` TEXT NOT NULL,
`shipping_code` TEXT NOT NULL,
`comment` text NOT NULL,
`total` decimal(15,4) NOT NULL DEFAULT '0.0000',
`order_status_id` INT  NOT NULL DEFAULT '0',
-- `affiliate_id` INT  NOT NULL,
-- `commission` decimal(15,4) NOT NULL,
-- `marketing_id` INT  NOT NULL,
-- `tracking` TEXT NOT NULL,
`language_id` INT  NOT NULL,
`currency_id` INT  NOT NULL,
`currency_code` TEXT NOT NULL,
`currency_value` decimal(15,8) NOT NULL DEFAULT '1.00000000',
`ip` TEXT NOT NULL,
`forwarded_ip` TEXT NOT NULL,
`user_agent` TEXT NOT NULL,
`accept_language` TEXT NOT NULL,
`date_added` datetime NOT NULL,
`date_modified` datetime NOT NULL
-- PRIMARY KEY (`order_id`)
);





